version: '3.8'
services:
  backend:
    image: prog_image/api
    container_name: prog_image_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    volumes:
      - ./src/:/app/src
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PROGIMG_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PROGIMG_MONGODB_PASS}
      MONGO_INITDB_DATABASE: ${PROGIMG_MONGODB_DB}
    ports:
        - ${PROGIMG_MONGODB_PORT}:${PROGIMG_MONGODB_PORT}
    volumes:
        - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
